import type { LevelConfig } from '../types/game';

export const LEVEL_CONFIGS: Record<number, LevelConfig> = {
  1: {
    level: 1,
    targetTimeSeconds: 120,
    experienceGoal: 'Level 1 (Easy Tutorial): 92% match density, 120s timer. Relaxed introduction.',
    targetAddRowsMin: 0,
    targetAddRowsMax: 1,
    initialMatchDensity: 0.92,
    decoyRatio: 0.00,
    isReliefLevel: false,
    winProbabilityTarget: 1.00,
  },
  2: {
    level: 2,
    targetTimeSeconds: 110,
    experienceGoal: 'Level 2 (Mild Ramp): 85% match density, 110s timer.',
    targetAddRowsMin: 1,
    targetAddRowsMax: 2,
    initialMatchDensity: 0.85,
    decoyRatio: 0.02,
    isReliefLevel: false,
    winProbabilityTarget: 0.98,
  },
  3: {
    level: 3,
    targetTimeSeconds: 100,
    experienceGoal: 'Level 3 (Normal Baseline): 75% match density, 100s timer. Requires visual scanning.',
    targetAddRowsMin: 1,
    targetAddRowsMax: 2,
    initialMatchDensity: 0.75,
    decoyRatio: 0.04,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
  4: {
    level: 4,
    targetTimeSeconds: 95,
    experienceGoal: 'Level 4 (Moderate): 65% match density, 95s timer. Buried pairs and light decoys.',
    targetAddRowsMin: 1,
    targetAddRowsMax: 3,
    initialMatchDensity: 0.65,
    decoyRatio: 0.06,
    isReliefLevel: false,
    winProbabilityTarget: 0.92,
  },
  5: {
    level: 5,
    targetTimeSeconds: 90,
    experienceGoal: 'Level 5 (Challenging): 55% match density, 90s timer. Strategic planning required.',
    targetAddRowsMin: 2,
    targetAddRowsMax: 3,
    initialMatchDensity: 0.55,
    decoyRatio: 0.08,
    isReliefLevel: false,
    winProbabilityTarget: 0.90,
  },
  6: {
    level: 6,
    targetTimeSeconds: 85,
    experienceGoal: 'Level 6 (Advanced): 48% match density, 85s timer. Scanning depth.',
    targetAddRowsMin: 2,
    targetAddRowsMax: 3,
    initialMatchDensity: 0.48,
    decoyRatio: 0.11,
    isReliefLevel: false,
    winProbabilityTarget: 0.88,
  },
  7: {
    level: 7,
    targetTimeSeconds: 80,
    experienceGoal: 'Level 7 (Expert Ramp): 42% match density, 80s timer. Mild decoy friction.',
    targetAddRowsMin: 2,
    targetAddRowsMax: 4,
    initialMatchDensity: 0.42,
    decoyRatio: 0.14,
    isReliefLevel: false,
    winProbabilityTarget: 0.85,
  },
  8: {
    level: 8,
    targetTimeSeconds: 75,
    experienceGoal: 'Level 8 (Expert): 36% match density, 75s timer.',
    targetAddRowsMin: 2,
    targetAddRowsMax: 4,
    initialMatchDensity: 0.36,
    decoyRatio: 0.17,
    isReliefLevel: false,
    winProbabilityTarget: 0.82,
  },
  9: {
    level: 9,
    targetTimeSeconds: 70,
    experienceGoal: 'Level 9 (High Challenge): 30% match density, 70s timer.',
    targetAddRowsMin: 3,
    targetAddRowsMax: 4,
    initialMatchDensity: 0.30,
    decoyRatio: 0.20,
    isReliefLevel: false,
    winProbabilityTarget: 0.80,
  },
  10: {
    level: 10,
    targetTimeSeconds: 65,
    experienceGoal: 'Level 10 (Master): 25% match density, 65s timer. Precise matching.',
    targetAddRowsMin: 3,
    targetAddRowsMax: 4,
    initialMatchDensity: 0.25,
    decoyRatio: 0.24,
    isReliefLevel: false,
    winProbabilityTarget: 0.78,
  },
  11: {
    level: 11,
    targetTimeSeconds: 62,
    experienceGoal: 'Level 11 (Master Ramp): 20% match density, 62s timer.',
    targetAddRowsMin: 3,
    targetAddRowsMax: 5,
    initialMatchDensity: 0.20,
    decoyRatio: 0.28,
    isReliefLevel: false,
    winProbabilityTarget: 0.75,
  },
  12: {
    level: 12,
    targetTimeSeconds: 60,
    experienceGoal: 'Level 12 (Grandmaster): 16% match density, 60s timer.',
    targetAddRowsMin: 3,
    targetAddRowsMax: 5,
    initialMatchDensity: 0.16,
    decoyRatio: 0.32,
    isReliefLevel: false,
    winProbabilityTarget: 0.72,
  },
  13: {
    level: 13,
    targetTimeSeconds: 58,
    experienceGoal: 'Level 13 (Grandmaster Peak): 12% match density, 58s timer.',
    targetAddRowsMin: 4,
    targetAddRowsMax: 5,
    initialMatchDensity: 0.12,
    decoyRatio: 0.36,
    isReliefLevel: false,
    winProbabilityTarget: 0.70,
  },
  14: {
    level: 14,
    targetTimeSeconds: 55,
    experienceGoal: 'Level 14 (Legend): 8% match density, 55s timer.',
    targetAddRowsMin: 4,
    targetAddRowsMax: 5,
    initialMatchDensity: 0.08,
    decoyRatio: 0.40,
    isReliefLevel: false,
    winProbabilityTarget: 0.68,
  },
  15: {
    level: 15,
    targetTimeSeconds: 50,
    experienceGoal: 'Level 15 (Ultimate Test): 5% match density, 50s timer.',
    targetAddRowsMin: 4,
    targetAddRowsMax: 6,
    initialMatchDensity: 0.05,
    decoyRatio: 0.45,
    isReliefLevel: false,
    winProbabilityTarget: 0.65,
  },
};

export function getLevelConfig(level: number): LevelConfig {
  if (LEVEL_CONFIGS[level]) {
    return LEVEL_CONFIGS[level];
  }
  
  const extraLevels = level - 15;
  const initialMatchDensity = Math.max(0.02, 0.05 - extraLevels * 0.002);
  const decoyRatio = Math.min(0.50, 0.45 + extraLevels * 0.005);
  const targetTimeSeconds = Math.max(45, 50 - Math.floor(extraLevels * 0.2));

  return {
    level,
    targetTimeSeconds,
    experienceGoal: `Level ${level} (Master Challenge): High friction, precise strategy required.`,
    targetAddRowsMin: 4,
    targetAddRowsMax: 6,
    initialMatchDensity,
    decoyRatio,
    isReliefLevel: false,
    winProbabilityTarget: Math.max(0.50, 0.65 - extraLevels * 0.01),
  };
}
