import type { LevelConfig } from '../types/game';

export const LEVEL_CONFIGS: Record<number, LevelConfig> = {
  1: {
    level: 1,
    targetTimeSeconds: 120,
    experienceGoal: 'Super Easy. 90% match density. Instant fun & fast completion.',
    targetAddRowsMin: 0,
    targetAddRowsMax: 1,
    initialMatchDensity: 0.90,
    decoyRatio: 0.05,
    isReliefLevel: false,
    winProbabilityTarget: 0.99,
  },
  2: {
    level: 2,
    targetTimeSeconds: 150,
    experienceGoal: 'Easy. High match density and low friction.',
    targetAddRowsMin: 1,
    targetAddRowsMax: 2,
    initialMatchDensity: 0.80,
    decoyRatio: 0.10,
    isReliefLevel: false,
    winProbabilityTarget: 0.98,
  },
  3: {
    level: 3,
    targetTimeSeconds: 180,
    experienceGoal: 'Relaxed. Plenty of open matches.',
    targetAddRowsMin: 1,
    targetAddRowsMax: 2,
    initialMatchDensity: 0.70,
    decoyRatio: 0.15,
    isReliefLevel: false,
    winProbabilityTarget: 0.98,
  },
  4: {
    level: 4,
    targetTimeSeconds: 210,
    experienceGoal: 'Moderate. Easy scanning with light depth.',
    targetAddRowsMin: 2,
    targetAddRowsMax: 3,
    initialMatchDensity: 0.60,
    decoyRatio: 0.20,
    isReliefLevel: false,
    winProbabilityTarget: 0.97,
  },
  5: {
    level: 5,
    targetTimeSeconds: 240,
    experienceGoal: 'Balanced. Fun challenge with generous time.',
    targetAddRowsMin: 2,
    targetAddRowsMax: 3,
    initialMatchDensity: 0.50,
    decoyRatio: 0.25,
    isReliefLevel: false,
    winProbabilityTarget: 0.96,
  },
  6: {
    level: 6,
    targetTimeSeconds: 180,
    experienceGoal: 'Relief Level (Drop). Super fast cleanup experience.',
    targetAddRowsMin: 1,
    targetAddRowsMax: 2,
    initialMatchDensity: 0.80,
    decoyRatio: 0.10,
    isReliefLevel: true,
    winProbabilityTarget: 0.99,
  },
  7: {
    level: 7,
    targetTimeSeconds: 240,
    experienceGoal: 'Smooth Ramp. Generous target time.',
    targetAddRowsMin: 2,
    targetAddRowsMax: 3,
    initialMatchDensity: 0.55,
    decoyRatio: 0.25,
    isReliefLevel: false,
    winProbabilityTarget: 0.96,
  },
  8: {
    level: 8,
    targetTimeSeconds: 270,
    experienceGoal: 'Engaging. Good balance of density and space.',
    targetAddRowsMin: 2,
    targetAddRowsMax: 4,
    initialMatchDensity: 0.50,
    decoyRatio: 0.30,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
  9: {
    level: 9,
    targetTimeSeconds: 300,
    experienceGoal: 'Advanced. Plenty of time to scan and clear.',
    targetAddRowsMin: 3,
    targetAddRowsMax: 4,
    initialMatchDensity: 0.45,
    decoyRatio: 0.35,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
  10: {
    level: 10,
    targetTimeSeconds: 330,
    experienceGoal: 'Peak Master. Rich matches with 5.5 min time limit.',
    targetAddRowsMin: 3,
    targetAddRowsMax: 5,
    initialMatchDensity: 0.40,
    decoyRatio: 0.40,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
  11: {
    level: 11,
    targetTimeSeconds: 210,
    experienceGoal: 'Relief Level (Drop). Satisfying cleanup phase.',
    targetAddRowsMin: 2,
    targetAddRowsMax: 3,
    initialMatchDensity: 0.75,
    decoyRatio: 0.15,
    isReliefLevel: true,
    winProbabilityTarget: 0.98,
  },
  12: {
    level: 12,
    targetTimeSeconds: 270,
    experienceGoal: 'Post-Relief Ramp. Smooth progression.',
    targetAddRowsMin: 3,
    targetAddRowsMax: 4,
    initialMatchDensity: 0.50,
    decoyRatio: 0.30,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
  13: {
    level: 13,
    targetTimeSeconds: 300,
    experienceGoal: 'Strategic. Plenty of time and add-row budget.',
    targetAddRowsMin: 3,
    targetAddRowsMax: 5,
    initialMatchDensity: 0.45,
    decoyRatio: 0.35,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
  14: {
    level: 14,
    targetTimeSeconds: 330,
    experienceGoal: 'High Challenge. Generous 5.5 min time allowance.',
    targetAddRowsMin: 4,
    targetAddRowsMax: 5,
    initialMatchDensity: 0.40,
    decoyRatio: 0.40,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
  15: {
    level: 15,
    targetTimeSeconds: 360,
    experienceGoal: 'Grandmaster Peak. 6 full minutes to solve.',
    targetAddRowsMin: 4,
    targetAddRowsMax: 6,
    initialMatchDensity: 0.35,
    decoyRatio: 0.45,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
};

export function getLevelConfig(level: number): LevelConfig {
  if (LEVEL_CONFIGS[level]) {
    return LEVEL_CONFIGS[level];
  }
  const cycleIndex = (level - 1) % 5;
  const isRelief = cycleIndex === 0 && level > 1;
  
  if (isRelief) {
    return {
      level,
      targetTimeSeconds: 210 + Math.floor(level / 5) * 20,
      experienceGoal: 'Relief Level (Drop). Refreshing cleanup experience.',
      targetAddRowsMin: 2,
      targetAddRowsMax: 3,
      initialMatchDensity: 0.75,
      decoyRatio: 0.15,
      isReliefLevel: true,
      winProbabilityTarget: 0.98,
    };
  }

  const ramp = cycleIndex / 4.0;
  const baseTime = 240 + Math.floor(level / 5) * 30;
  return {
    level,
    targetTimeSeconds: Math.floor(baseTime + ramp * 60),
    experienceGoal: `Sawtooth Level ${level}. Ramping difficulty.`,
    targetAddRowsMin: Math.min(5, 2 + Math.floor(level / 4)),
    targetAddRowsMax: 6,
    initialMatchDensity: Math.max(0.35, 0.70 - ramp * 0.30),
    decoyRatio: Math.min(0.50, 0.20 + ramp * 0.30),
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  };
}
