import type { LevelConfig } from '../types/game';

export const LEVEL_CONFIGS: Record<number, LevelConfig> = {
  1: {
    level: 1,
    targetTimeSeconds: 45,
    experienceGoal: 'Easy. 70% match density. Instant gratification.',
    targetAddRowsMin: 1,
    targetAddRowsMax: 1,
    initialMatchDensity: 0.70,
    decoyRatio: 0.10,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
  2: {
    level: 2,
    targetTimeSeconds: 65,
    experienceGoal: 'Mild Ramp. Moderate initial matches.',
    targetAddRowsMin: 1,
    targetAddRowsMax: 2,
    initialMatchDensity: 0.55,
    decoyRatio: 0.20,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
  3: {
    level: 3,
    targetTimeSeconds: 90,
    experienceGoal: 'Normal. Requires visual scanning.',
    targetAddRowsMin: 2,
    targetAddRowsMax: 3,
    initialMatchDensity: 0.40,
    decoyRatio: 0.35,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
  4: {
    level: 4,
    targetTimeSeconds: 120,
    experienceGoal: 'Challenging. Matches buried behind light friction.',
    targetAddRowsMin: 2,
    targetAddRowsMax: 3,
    initialMatchDensity: 0.30,
    decoyRatio: 0.50,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
  5: {
    level: 5,
    targetTimeSeconds: 150,
    experienceGoal: 'Hard. Matches buried behind decoys.',
    targetAddRowsMin: 2,
    targetAddRowsMax: 3,
    initialMatchDensity: 0.20,
    decoyRatio: 0.65,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
  6: {
    level: 6,
    targetTimeSeconds: 90,
    experienceGoal: 'Relief Level (Drop). Breath of fresh air, back to Normal.',
    targetAddRowsMin: 2,
    targetAddRowsMax: 4,
    initialMatchDensity: 0.45,
    decoyRatio: 0.30,
    isReliefLevel: true,
    winProbabilityTarget: 0.95,
  },
  7: {
    level: 7,
    targetTimeSeconds: 120,
    experienceGoal: 'Ramp Up. Increasing friction and decoy depth.',
    targetAddRowsMin: 3,
    targetAddRowsMax: 4,
    initialMatchDensity: 0.35,
    decoyRatio: 0.45,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
  8: {
    level: 8,
    targetTimeSeconds: 160,
    experienceGoal: 'Harder. Deeper decoy layers.',
    targetAddRowsMin: 3,
    targetAddRowsMax: 4,
    initialMatchDensity: 0.22,
    decoyRatio: 0.60,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
  9: {
    level: 9,
    targetTimeSeconds: 185,
    experienceGoal: 'Expert. Complex sequence scanning.',
    targetAddRowsMin: 4,
    targetAddRowsMax: 5,
    initialMatchDensity: 0.15,
    decoyRatio: 0.70,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
  10: {
    level: 10,
    targetTimeSeconds: 210,
    experienceGoal: 'Peak Master. High decoy friction, multiple add-rows required.',
    targetAddRowsMin: 4,
    targetAddRowsMax: 5,
    initialMatchDensity: 0.10,
    decoyRatio: 0.75,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
  11: {
    level: 11,
    targetTimeSeconds: 110,
    experienceGoal: 'Relief Level (Drop). Satisfying cleanup phase.',
    targetAddRowsMin: 3,
    targetAddRowsMax: 4,
    initialMatchDensity: 0.40,
    decoyRatio: 0.35,
    isReliefLevel: true,
    winProbabilityTarget: 0.95,
  },
  12: {
    level: 12,
    targetTimeSeconds: 140,
    experienceGoal: 'Ramp Up. Post-relief scaling.',
    targetAddRowsMin: 3,
    targetAddRowsMax: 5,
    initialMatchDensity: 0.30,
    decoyRatio: 0.50,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
  13: {
    level: 13,
    targetTimeSeconds: 180,
    experienceGoal: 'High Challenge. Strategic add-row usage required.',
    targetAddRowsMin: 4,
    targetAddRowsMax: 5,
    initialMatchDensity: 0.20,
    decoyRatio: 0.65,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
  14: {
    level: 14,
    targetTimeSeconds: 220,
    experienceGoal: 'Extreme Challenge. Deeply layered pairs.',
    targetAddRowsMin: 4,
    targetAddRowsMax: 6,
    initialMatchDensity: 0.12,
    decoyRatio: 0.72,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
  15: {
    level: 15,
    targetTimeSeconds: 250,
    experienceGoal: 'Grandmaster Peak. Precise execution needed.',
    targetAddRowsMin: 5,
    targetAddRowsMax: 6,
    initialMatchDensity: 0.08,
    decoyRatio: 0.80,
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  },
};

export function getLevelConfig(level: number): LevelConfig {
  if (LEVEL_CONFIGS[level]) {
    return LEVEL_CONFIGS[level];
  }
  const cycleIndex = (level - 1) % 5;
  const isRelief = cycleIndex === 0 && level > 1;
  
  if (isRelief) {
    return {
      level,
      targetTimeSeconds: 100 + Math.floor(level / 5) * 10,
      experienceGoal: 'Relief Level (Drop). Refreshing cleanup experience.',
      targetAddRowsMin: 3,
      targetAddRowsMax: 4,
      initialMatchDensity: 0.40,
      decoyRatio: 0.35,
      isReliefLevel: true,
      winProbabilityTarget: 0.95,
    };
  }

  const ramp = cycleIndex / 4.0;
  const baseTime = 120 + Math.floor(level / 5) * 40;
  return {
    level,
    targetTimeSeconds: Math.floor(baseTime + ramp * 100),
    experienceGoal: `Sawtooth Level ${level}. Ramping difficulty.`,
    targetAddRowsMin: Math.min(5, 2 + Math.floor(level / 4)),
    targetAddRowsMax: 6,
    initialMatchDensity: Math.max(0.08, 0.50 - ramp * 0.40),
    decoyRatio: Math.min(0.85, 0.30 + ramp * 0.50),
    isReliefLevel: false,
    winProbabilityTarget: 0.95,
  };
}
